// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui.h"

extern int led;

/** Request the C++ application loop to drive the LED output high. */
void TurnOn(lv_event_t * e)
{
    (void)e;
    led = 1;
}

/** Request the C++ application loop to drive the LED output low. */
void TurnOff(lv_event_t * e)
{
    (void)e;
    led = 0;
}
