// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui.h"

extern int led;

/*---------------------------------------------------------------
 * Button event callbacks
 * Keep the application LED state synchronized with the generated UI.
 *--------------------------------------------------------------*/
/**
 * @brief Request the application to turn the LED on.
 * @param e LVGL event context (unused by this callback).
 */
void TurnOn(lv_event_t * e)
{
	led = 1;
}

/**
 * @brief Request the application to turn the LED off.
 * @param e LVGL event context (unused by this callback).
 */
void TurnOff(lv_event_t * e)
{
	led = 0;
}
